// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  faqs: dynamic(() => import("./Faqs")),
  feature_list: dynamic(() => import("./FeatureList")),
  testimonials: dynamic(() => import("./Testimonials")),
  three_cards: dynamic(() => import("./ThreeColumnCards")),
};
